app/models.py
#!/usr/bin/env python
#coding:utf-8

from . import db

class User(db.Model):
    __tablename__ = 'User'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    age = db.Column(db.Integer)
    sex = db.Column(db.Integer)

    def __repr__(self):
        return '<User %s>' % self.name

app/__init__.py
#!/usr/bin/env python
#coding:utf-8

import logging
from logging.handlers import RotatingFileHandler
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import config
from .api.views import api
from .admin.views import admin
from .blog.views import blog
db = SQLAlchemy()

def setupLogging(level):
    logging.basicConfig(level=level)
    file_log_handler = RotatingFileHandler('logs/log', maxBytes=1024*1024*100, backupCount=10)
    formatter = logging.Formatter('%(asctime)s %(levelname)s %(filename)s:%(lineno)d %(message)s')
    file_log_handler.setFormatter(formatter)
    logging.getLogger().addHandler(file_log_handler)

def create_app(config_name='default'):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    setupLogging(config[config_name].LOGGING_LEVEL)
    db.init_app(app)

    app.register_blueprint(api)
    app.register_blueprint(admin)
    app.register_blueprint(blog)

    return app

app/admin/views.py
#!/usr/bin/env python
#coding:utf-8

from flask import make_response, jsonify, current_app
from flask import Blueprint
admin = Blueprint('admin', __name__, url_prefix='/admin')

@admin.route('/', methods=["GET"])
def index():
    current_app.logger.info('open page admin')
    resp = make_response(jsonify({'ret': 0}))
    resp.set_cookie('test', '123')
    resp.headers['content-type'] = 'application/json'
    return resp

@admin.app_errorhandler(404)
def page_not_found(e):
    return '<h1 style="text-align:center;color:red;">404  page not found</h1>', 404

app/api/__init__.py
#!/usr/bin/env python
#coding:utf-8

app/api/views.py
#!/usr/bin/env python
#coding:utf-8

from flask import Blueprint

api = Blueprint('api', __name__, url_prefix='/api')

@api.route('/', methods=["GET", "POST"])
def index():
    return 'hello world'

# @api.app_errorhandler(404)
# def page_not_founc(e):
#     return '<h1 style="text-align:center;">404</h1><h1 style="text-align:center;">page not found</h1>', 404
#

app/blog/views.py
#!/usr/bin/env python
#coding:utf-8

from flask import Blueprint, render_template
from datetime import  datetime
blog = Blueprint('blog', __name__)

@blog.route('/', methods=['GET'])
def index():
    args = {'blog_list': [
        {'url': '#', 'title': u'测试', 'img_url': '', 'content': u'论编程语言的鄙视链', 'time_create': datetime.now()},
    ]}
    return render_template('blog/index.html', **args)

@blog.route('/about', methods=['GET'])
def about():
    return render_template('blog/about.html')

@blog.route('/shuo', methods=['GET'])
def shuo():
    return

@blog.route('/diary', methods=['GET'])
def diary():
    return

@blog.route('/photo', methods=['GET'])
def photo():
    return render_template('blog/photo.html')

@blog.route('/learn', methods=['GET'])
def learn():
    return

@blog.route('/guestbook', methods=['GET', 'POST'])
def guestbook():
    return

@blog.route('/<int:id>.html')
def info(id):
    return str(id)

app/templates/blog/about.html
{% extends "blog/base.html" %}

{% block title %}关于我-个人博客{% endblock %}

{% block content %}
    <div class="left" id="about_me">
        <div class="weizi">
            <div class="wz_text">当前位置：<a href="{{ url_for('blog.index') }}">首页</a> > <h1>关于我</h1></div>
        </div>
        <div class="about_content">万花凋落尽，一梅独傲霜。暗香疏影处，凌风踏雪来。</div>
    </div>
    <div class="right" id="c_right">
        <div class="s_about">
            <div id="calendar"></div>
        </div>
    </div>
    <div class="clear"></div>
    <script>new calendar('calendar')</script>
{% endblock %}

{% block footer %}
    {{ super() }}
{% endblock %}

app/templates/blog/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="Generator" content="">
    <meta name="Author" content="">
    <meta name="Keywords" content="个人博客">
    <meta name="Description" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <link rel="stylesheet" href="{{ url_for('static', filename='blog/css/index.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='blog/css/style.css') }}">
    <script src="{{ url_for('static', filename='blog/js/jquery1.42.min.js') }}"></script>
    <script src="{{ url_for('static', filename='blog/js/jquery.SuperSlide.2.1.1.js') }}"></script>
    <script src="{{ url_for('static', filename='blog/js/calendar.js') }}"></script>
    <!--[if lt IE 9]>
    <script src="{{ url_for('static', filename='blog/js/html5.js') }}"></script>
    <![endif]-->
    <title>{% block title %}个人博客{% endblock %}</title>
    {% block head_import %}{% endblock %}
</head>
<body>
{% block body %}
    <div id="header">
        {% block header %}
        <h1>个人博客</h1>
        <p>青春是打开了,就合不上的书。人生是踏上了，就回不了头的路，爱情是扔出了，就收不回的赌注。</p>
        <div id="nav">
            <div id="nav_left">
                <ul>
                <li><a href="{{ url_for('blog.index') }}">首页</a></li>
                <li><a href="{{ url_for('blog.about') }}">关于我</a></li>
                <li><a href="{{ url_for('blog.shuo') }}">碎言碎语</a></li>
                <li><a href="{{ url_for('blog.diary') }}">个人日记</a></li>
                <li><a href="{{ url_for('blog.photo') }}">相册展示</a></li>
                <li><a href="{{ url_for('blog.learn') }}">学无止境</a></li>
                <li><a href="{{ url_for('blog.guestbook') }}">留言板</a></li>
                <div class="clear"></div>
            </ul>
            </div>
            <div id="nav_right">
                <span class="item-text" id="login">登陆</span> / <span class="item-text" id="register">注册</span>
            </div>
        </div>
        {% endblock %}
    </div>
    <div id="content">
        {% block content %}

        {% endblock %}
    </div>
    <div id="footer">
        {% block footer %}
        <p>Design by:<a href="#">xxx</a></p>
        {% endblock %}
    </div>
    {% block script %}
        <script>
            jQuery('.lanmubox').slide({easing: 'easeOutBounce', delayTime: 400})
        </script>
        <script src="{{ url_for('static', filename='blog/js/nav.js') }}"></script>
    {% endblock %}
{% endblock %}
</body>
</html>

app/templates/blog/index.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="left" id="c_left">
        <div class="s_tuijian"><h2>文章<span>推荐</span></h2></div>
        <div class="content_text">
        {% for item in blog_list %}
            <div class="wz">
                <h3><a href="{{ item.url }}" title="{{ item.title }}">{{ item.title }}</a></h3>
                <dl>
                    <dt>
                    {% if item.img_url and item.img_url != '' %}
                        <img src="{{ item.img_url }}" width="200" height="123" alt="">
                    {% else %}
                        <img src="{{ url_for('static', filename='blog/images/photo/10.jpg') }}" width="200" height="123" alt="">
                    {% endif %}
                    </dt>
                    <dd>
                        <p class="dd_text_1">{{ item.content }}</p>
                        <p class="dd_text_2">
                            <span class="left author">孤狼</span>
                            <span class="left sj">时间：{{ item.time_create }}</span>
                            <span class="left fl">分类：<a href="#" title=""></a></span>
                            <span class="left yd"><a href="#" title="阅读全文">阅读全文</a></span>
                            <div class="clear"></div>
                        </p>
                    </dd>
                    <div class="clear"></div>
                </dl>
            </div>
        {% endfor %}
        </div>
    </div>
    <div class="right" id="c_right">
        <div class="s_about">
{#            <h2>关于博主</h2>#}
{#            <img src="{{ url_for('static', filename='blog/images/my.jpg') }}" width="230" height="230" alt="博主">#}
{#            <p>博主：XXX</p>#}
{#            <p>职业：搬砖</p>#}
{#            <p>简介：</p>#}
{#            <p>#}
{#                <a href="tencent://message/?Site=baidu.com&uin=1107756736&Menu=yes" title="联系博主"><span class="left b_1"></span></a><a href="" title="加入QQ群，一起学习！"><span class="left b_2"></span></a>#}
{#                <div class="clear"></div>#}
{#            </p>#}
            <div id="calendar"></div>
        </div>
        <div class="lanmubox">
            <div class="hd">
                <ul>
                    <li>精心推荐</li>
                    <li>最新文章</li>
                    <li class="hd_3">随机文章</li>
                </ul>
            </div>
            <div class="bd">
                <ul>
                <li><a href="" title="网站项目实战开发">网站项目实战开发</a></li>
                <li><a href="" title="网站项目实战开发">网站项目实战开发</a></li>
                <li><a href="" title="网站项目实战开发">网站项目实战开发</a></li>
                <li><a href="" title="网站项目实战开发">网站项目实战开发</a></li>
                <li><a href="" title="网站项目实战开发">网站项目实战开发</a></li>
            </ul>
                <ul>
                <li><a href="" title="关于响应式布局">关于响应式布局</a></li>
                <li><a href="" title="关于响应式布局">关于响应式布局</a></li>
                <li><a href="" title="关于响应式布局">关于响应式布局</a></li>
                <li><a href="" title="关于响应式布局">关于响应式布局</a></li>
                <li><a href="" title="关于响应式布局">关于响应式布局</a></li>
            </ul>
                <ul>
                <li><a href="" title="如何创建个人博客网站">如何创建个人博客网站</a></li>
                <li><a href="" title="如何创建个人博客网站">如何创建个人博客网站</a></li>
                <li><a href="" title="如何创建个人博客网站">如何创建个人博客网站</a></li>
                <li><a href="" title="如何创建个人博客网站">如何创建个人博客网站</a></li>
                <li><a href="" title="如何创建个人博客网站">如何创建个人博客网站</a></li>
            </ul>
            </div>
        </div>
        <div class="link">
            <h2>友情链接</h2>
            <p><a href="https://www.cnblogs.com/" target="_blank">博客园</a></p>
        </div>
    </div>
    <div class="clear"></div>
    <script>
        new calendar('calendar');
    </script>
{% endblock %}

app/templates/blog/photo.html
{% extends "blog/base.html" %}

{% block title %}相册展示-个人博客{% endblock %}

{% block head_import %}
    <script src="{{ url_for('static', filename='blog/js/common.js') }}"></script>
    <script src="{{ url_for('static', filename='blog/js/waterfall.js') }}"></script>
{% endblock %}

{% block content %}
    <div id="content_xc">
        <div class="weizi">
            <div class="wz_text">当前位置：<a href="{{ url_for('blog.index') }}">首页</a> > <h1>相册展示</h1></div>
        </div>
        <div class="xc_content">
            <div class="con-bg">
                <div class="w960 mt_10">
                    <div class="w650">
                        <ul class="tips" id="wf-main" style="display:none">
                            <li class="wf-cld"><img src="{{ url_for('static', filename='blog/images/photo/8.jpg') }}" width="200" height="178" alt="" /></li>
                            <li class="wf-cld"><img src="{{ url_for('static', filename='blog/images/photo/1.jpg') }}" width="200" height="147" alt="" /></li>
                            <li class="wf-cld"><img src="{{ url_for('static', filename='blog/images/photo/2.jpg') }}" width="200" height="267" alt="" /></li>
                            <li class="wf-cld"><img src="{{ url_for('static', filename='blog/images/photo/3.jpg') }}" width="200" height="125" alt="" /></li>
                            <li class="wf-cld"><img src="{{ url_for('static', filename='blog/images/photo/4.jpg') }}" width="200" height="199" alt="" /></li>
                            <li class="wf-cld"><img src="{{ url_for('static', filename='blog/images/photo/5.jpg') }}" width="200" height="125" alt="" /></li>
                            <li class="wf-cld"><img src="{{ url_for('static', filename='blog/images/photo/6.jpg') }}" width="200" height="267" alt="" /></li>
                            <li class="wf-cld"><img src="{{ url_for('static', filename='blog/images/photo/7.jpg') }}" width="200" height="135" alt="" /></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    {{ super() }}
    <script>
        var timer, m = 0, m1 = $("img[rel='lazy']").length;
        function fade() {
            $("img[rel='lazy']").each(function () {
                var $scroTop = $(this).offset();
                if ($scroTop.top <= $(window).scrollTop() + $(window).height()) {
                    $(this).hide();
                    $(this).attr("src", $(this).attr("lazy_src"));
                    $(this).attr("top", $scroTop.top);
                    $(this).removeAttr("rel");
                    $(this).removeAttr("lazy_src");
                    $(this).fadeIn(600);
                    var _left = $(this).parent().parent().attr("_left");
                    if (_left != undefined)
                        $(this).parent().parent().animate({left: _left}, 400);
                    m++;
                }
            });
            if (m < m1) {
                timer = window.setTimeout(fade, 300);
            }
            else {
                window.clearTimeout(timer);
            }
        }
        $(function () {
            $("#wf-main img[rel='lazy']").each(function (i) {
                var _left = $(this).parent().parent().css("left").replace("px", "");
                $(this).parent().parent().attr("_left", _left);
                $(this).parent().parent().css("left", 0);
            });
            fade();
        });
        $(".loading").hide();
        $("#wf-main").show();
    </script>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="Generator" content="">
    <meta name="Author" content="">
    <meta name="Keywords" content="">
    <meta name="Description" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <title>Title</title>
</head>
<body>
hello world
</body>
</html>